[MIG][17.0] sale_order_line_position: Migration to 17.0
xaviedoanhduy/sale-reporting pull request #1
Opened 2024-04-17 12:13 UTC by xaviedoanhduy

2024-04-19 08:34 UTC, nguyenminhchien requested changes

2024-04-19 08:34 UTC, nguyenminhchien commented on sale_order_line_position/models/ir_actions_report.py
> +    def render_qweb_pdf(self, res_ids=None, data=None):
it should be `def _render_qweb_pdf()`. btw, you must make sure the positions are recomputed when printing the Quotation / Order report.

2024-04-19 08:34 UTC, nguyenminhchien commented on sale_order_line_position/models/ir_actions_report.py
> +    def render_qweb_pdf(self, res_ids=None, data=None):
it's better if you create a unit test for this. so, we don't miss this point next time of the migration.

2024-04-23 02:45 UTC, nguyenminhchien requested changes

2024-04-23 02:45 UTC, nguyenminhchien commented on sale_order_line_position/models/ir_actions_report.py
> +        if active_model == "sale.order":
```
        report_sudo = self._get_report(report_ref)
        if report_sudo.model == "sale.order":
            sales = self.env["sale.order"].browse(res_ids)
            sales.recompute_positions()
```

2024-04-23 02:45 UTC, nguyenminhchien commented on sale_order_line_position/static/description/index.html
> +<?xml version="1.0" encoding="utf-8"?>
remove this line

2024-04-23 07:21 UTC, xaviedoanhduy commented
Thanks for reviewing. The PR commit was changed accordingly.

2024-04-23 07:28 UTC, nguyenminhchien approved these changes

2024-05-16 02:56 UTC, closed without merging